# Generated by Django 4.1.7 on 2023-02-27 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('time', models.TimeField(default=datetime.datetime.now)),
                ('amounts', models.ImageField(default=0, upload_to='')),
            ],
        ),
    ]
