# Generated by Django 4.1.7 on 2023-02-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'electronics'), ('Home', 'home'), ('Clothes', 'clothes')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='amounts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
