# Generated by Django 4.1.7 on 2023-02-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category_alter_product_amounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='products-photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Home', 'Home'), ('Clothes', 'Clothes')], max_length=20),
        ),
    ]
